import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { readFileSync } from "node:fs";
test("six-month debt activity counts payments and actual progress stays fixed after a balance check", async ({ page }) => {
 const fixture=JSON.parse(readFileSync("tests/fixtures/legacy-v0.json","utf8"));
 const date=new Date().toISOString().slice(0,10);
 fixture.accounts=[{...fixture.accounts[0],id:"activity-card",name:"Citi1",balance:1000,baselineBalance:1000,balanceOffset:-100,apr:0,interestFee:0,archivedAt:null}];
 const entry={accountId:"activity-card",date,createdAt:date+"T12:00:00Z",updatedAt:date+"T12:00:00Z",deletedAt:null,payeeId:"",payeeName:"Citi1",category:"Debt payment",memo:"",debtAction:"payment"};
 fixture.transactions=[{...entry,id:"payment-1",type:"payment",amount:100,title:"First payment"},{...entry,id:"payment-2",type:"payment",amount:200,title:"Second payment"},{...entry,id:"interest",type:"fee",category:"Interest",debtAction:undefined,amount:50,title:"Statement interest"}];
 fixture.balanceAdjustments=[{id:"balance-check",accountId:"activity-card",date,createdAt:date+"T13:00:00Z",difference:-100,balanceBefore:750,balanceAfter:650,note:"Lender balance correction"}];
 fixture.snapshots=[];
 await page.goto("/");
 await page.locator('input[type="file"]').setInputFiles({name:"activity.json",mimeType:"application/json",buffer:Buffer.from(JSON.stringify(fixture))});
 const card=page.locator(".balance-first-cards>article").filter({has:page.getByRole("heading",{name:"Citi1",exact:true})});
 await expect(page.locator(".debts-screen > :last-child")).toHaveClass("loan-progress-section");
 const history=card.locator(".debt-history");
 await history.locator(':scope > summary').click();
 await expect(history.locator(".debt-history-month")).toHaveCount(1);
 await expect(history.locator("details")).toHaveCount(0);
 await expect(history.locator(".inline-captured-balance").filter({hasText:"$750.00 → $650.00"})).toHaveCount(1);
 await expect(history.locator(".debt-history-month").first()).toContainText("2 payments recorded · $300.00");
 await expect(history).toContainText("+$50.00");
 await expect(history).toContainText("−$100.00");
 await expect(history).not.toContainText("No activity recorded for this month");
 await expect(card.locator(".debt-progress-ring")).toHaveAttribute("aria-valuenow", "35");
 const centered=await card.evaluate(element=>{const card=element.getBoundingClientRect();const ring=element.querySelector('.debt-progress-ring')!.getBoundingClientRect();return Math.abs(card.x+card.width/2-ring.x-ring.width/2)<2;});
 expect(centered).toBe(true);
 expect(await history.locator('.inline-activity-entry').first().evaluate(e=>e.getBoundingClientRect().height)).toBeLessThanOrEqual(48);
 const contrast=await new AxeBuilder({page}).include(".debts-screen").withRules(["color-contrast"]).analyze();expect(contrast.violations).toEqual([]);
 await page.getByRole("button",{name:"More",exact:true}).click();
 await page.getByRole("button",{name:"Progress",exact:true}).filter({visible:true}).click();
 await expect(page.getByRole("heading",{name:"Progress",exact:true})).toBeVisible();
 await expect(page.locator(".actual-progress-summary")).toContainText("$1,000.00");
 await expect(page.locator(".actual-progress-summary")).toContainText("$650.00");
 await expect(page.locator(".actual-progress-summary")).toContainText("$350.00");
 await expect(page.locator(".actual-month-card")).toContainText("$350.00 net decrease");
 await expect(page.locator(".actual-month-card")).toContainText("2 payments recorded");
 await expect(page.locator(".progress-story")).toContainText("Your debt is $350.00 lower.");
 await expect(page.locator(".progress-month-story")).toContainText("−$300.00");
 await expect(page.locator(".progress-month-story")).toContainText("+$50.00");
 await expect(page.locator(".progress-month-story")).toContainText("Other lender balance changes");
 await expect(page.locator(".progress-projection-card,.phase-nine-metrics")).toHaveCount(0);
 await page.getByText("Saved balance history ›",{exact:true}).click();
 await page.getByText("Monthly balance checks (0)",{exact:true}).click();
 await page.getByRole("button",{name:"Save this month's balance check",exact:true}).click();
 await expect(page.locator(".actual-progress-summary")).toContainText("$1,000.00");
 await page.reload();
 await page.getByRole("button",{name:"More",exact:true}).click();
 await page.getByRole("button",{name:"Progress",exact:true}).filter({visible:true}).click();
 await expect(page.locator(".actual-progress-summary")).toContainText("$350.00");
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 const result=await new AxeBuilder({page}).include(".actual-progress-screen").withRules(["color-contrast"]).analyze();
 expect(result.violations).toEqual([]);
});
