import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import AxeBuilder from '@axe-core/playwright';

test('loans persist, use Budget payments, and do not change existing debt balances', async ({ page }) => {
  const fixture = JSON.parse(readFileSync('tests/fixtures/legacy-v0.json', 'utf8'));
  const month = new Date().toLocaleDateString('en-CA', { timeZone: 'America/Los_Angeles' }).slice(0,7);
  fixture.monthlyBudgets = { [month]: [{ id:'home-bill', name:'Mortgage', kind:'expense', category:'Housing', amount:2000, paymentMethod:'debit', creditAccountId:'', createdAt:new Date().toISOString(), recurring:true }] };
  await page.goto('/');
  await page.locator('input[type="file"]').setInputFiles({ name:'loan-fixture.json', mimeType:'application/json', buffer:Buffer.from(JSON.stringify(fixture)) });
  const before = await page.locator('.simple-total>strong').innerText();
  await page.getByRole('button', { name:'+ Track loan', exact:true }).click();
  const dialog = page.getByRole('dialog', { name:'Loan progress' });
  await dialog.getByLabel('Loan name', { exact:true }).fill('Home');
  await dialog.getByLabel('Original loan amount').fill('100000');
  await dialog.getByLabel('Remaining amount').fill('80000');
  await dialog.getByLabel('Monthly payment from Budget').selectOption('home-bill');
  await dialog.getByRole('button', { name:'Save loan' }).click();
  const card = page.getByRole('article', { name:'Home loan progress' });
  await expect(card).toContainText('20.00% paid down');
  await expect(card).toContainText('$2,000.00');
  await expect(page.locator('.simple-total>strong')).toHaveText(before);
  await expect(page.getByRole('status').first()).toHaveText(/Saved on device/);
  await page.reload();
  await expect(card).toContainText('$80,000.00');
  await page.getByRole('button', {name:'Budget',exact:true}).click();
  await page.getByRole('button', {name:'Edit Mortgage',exact:true}).click();
  await page.getByRole('dialog').getByLabel('Monthly amount',{exact:true}).fill('2100');
  await page.getByRole('dialog').getByRole('button',{name:/Save/}).click();
  await page.getByRole('button',{name:'Debts',exact:true}).click();
  await expect(card).toContainText('$2,100.00');
  await page.getByRole('button',{name:'Update Home loan'}).click();
  await dialog.getByLabel('Remaining amount').fill('75000');
  await dialog.getByLabel('Balance type').selectOption('payoff');
  await dialog.getByRole('button',{name:'Save loan'}).click();
  await expect(card).toContainText('≈ 25.00% paid down');
  await expect(card).toContainText('accrued interest');
  await card.getByText('Balance history', {exact:true}).click();
  await expect(card.locator('details')).toContainText('$80,000.00');
  await expect(card.locator('details')).toContainText('$75,000.00');
  const axe = await new AxeBuilder({page}).include('.loan-progress-section').withRules(['color-contrast']).analyze();
  expect(axe.violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
});
