import { test, expect } from "@playwright/test";
import { readFileSync } from "node:fs";

test("calculator and plan save independently and plan reserves minimums within the total", async ({ page }) => {
  const fixture = JSON.parse(readFileSync("tests/fixtures/legacy-v0.json", "utf8"));
  fixture.transactions = [];
  fixture.snapshots = [];
  fixture.accounts = [0, 1].map(index => ({ ...fixture.accounts[0], id: `plan-${index}`, name: `Plan card ${index}`, balance: 10000, baselineBalance: 10000, apr: 0, interestFee: 0, promoEndDate: "", postPromoApr: 0, minimum: 900, minimumMode: "manual", payoffMode: "priority" }));
  fixture.monthlyPlan = { detailedSpendingTracking: false, months: {}, calculatorAmount: 3793 };
  fixture.strategy = "custom";
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles({ name: "split-plan.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(fixture)) });
  await page.getByRole("button", { name: "More", exact: true }).click();
  await page.getByRole("button", { name: "Payoff Calculator", exact: true }).click();
  await expect(page.getByLabel("Total monthly debt payment", { exact: true })).toHaveValue("3793");
  await expect(page.getByRole("button", { name: "Avalanche", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "More", exact: true }).click();
  await page.getByRole("button", { name: "Payoff Plan", exact: true }).click();
  await expect(page.getByLabel("Total monthly debt payment", { exact: true })).toHaveValue("");
  await page.getByLabel("Total monthly debt payment", { exact: true }).fill("1000");
  await expect(page.getByRole("alert")).toContainText("1800.00");
  await expect(page.locator(".plan-hero")).toHaveCount(0);
  await page.getByLabel("Total monthly debt payment", { exact: true }).fill("7000");
  await expect(page.locator(".plan-hero")).toContainText("3 months");
  const allocation = page.getByRole("region", { name: "Monthly payment allocation" });
  await expect(allocation).toContainText("Minimums $1,800.00 · Extra $5,200.00");
  await expect(allocation.locator(".allocation-card").first()).toContainText("$6,100.00");
  const currentMonth = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });
  await expect(allocation.getByRole("heading", { name: `${currentMonth} payment plan`, exact: true })).toBeVisible();
  await expect(allocation).toContainText("First projected month");
  await expect(page.getByRole("button", { name: "Custom", exact: true })).toHaveCount(0);
  const minimum = page.getByLabel("Minimum payment for Plan card 1", { exact: true });
  await minimum.fill("0");
  await page.getByRole("button", { name: "Save minimum for Plan card 1", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("Enter a minimum greater than $0.");
  await expect(allocation).toContainText("Minimums $1,800.00");
  await minimum.fill("1200");
  await page.getByRole("button", { name: "Save minimum for Plan card 1", exact: true }).click();
  await expect(allocation).toContainText("Minimums $2,100.00 · Extra $4,900.00");
  await expect(allocation.locator(".allocation-card").first()).toContainText("$900.00");
  await expect(allocation.locator(".allocation-card").nth(1)).toContainText("$6,100.00");
  await expect(page.locator(".plan-table tbody tr")).toHaveCount(3);
  expect(await page.getByLabel("Total monthly debt payment", { exact: true }).evaluate(input => Number.parseFloat(getComputedStyle(input.closest('.extra-control')!.querySelector('label')!).fontSize))).toBeGreaterThanOrEqual(14);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.reload();
  await page.getByRole("button", { name: "More", exact: true }).click();
  await page.getByRole("button", { name: "Payoff Plan", exact: true }).click();
  await expect(page.getByLabel("Total monthly debt payment", { exact: true })).toHaveValue("7000");
  await expect(page.getByLabel("Minimum payment for Plan card 1", { exact: true })).toHaveValue("1200");
  await page.getByRole("button", { name: "More", exact: true }).click();
  await page.getByRole("button", { name: "Payoff Calculator", exact: true }).click();
  await expect(page.getByLabel("Total monthly debt payment", { exact: true })).toHaveValue("7000");
  await page.getByRole("button", { name: "Debts", exact: true }).click();
  await expect(page.locator(".simple-total")).toContainText("$20,000.00");
  const card = page.locator(".balance-first-cards>article").filter({ has: page.getByRole("heading", { name: "Plan card 1", exact: true }) });
  await expect(card).toContainText("$1,200.00");
  await expect(card).toContainText("$10,000.00");
});

test("removing an isolated test account retains its last balance in Progress", async ({ page }) => {
  const fixture = JSON.parse(readFileSync("tests/fixtures/legacy-v0.json", "utf8"));
  fixture.transactions = [];
  fixture.snapshots = [];
  fixture.accounts = [{ ...fixture.accounts[0], id: "remove-test", name: "Removal test card", balance: 1000, baselineBalance: 1000, apr: 0, interestFee: 0 }];
  fixture.monthlyPlan = { detailedSpendingTracking: false, months: {}, progressStartingBalance: 1000 };
  await page.goto("/");
  await page.locator('input[type="file"]').setInputFiles({ name: "removal-test.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify(fixture)) });
  await page.getByRole("button", { name: "Edit debt details for Removal test card" }).click();
  await page.getByText("Advanced destructive action", { exact: true }).click();
  page.on("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "Permanently delete debt account", exact: true }).click();
  await page.getByRole("button", { name: "More", exact: true }).click();
  await page.getByRole("button", { name: "Progress", exact: true }).filter({ visible: true }).click();
  await expect(page.locator(".actual-progress-summary")).toContainText("$1,000.00");
  await page.getByText("Account details & activity", {exact:true}).click();
  await expect(page.getByText("Removed from Debts · last balance retained", { exact: true })).toBeVisible();
  await expect(page.locator(".progress-story")).toContainText("$0.00");
  await page.getByRole("button", { name: "Save snapshot", exact: true }).click();
  await expect(page.locator(".snapshot-controls .saved-check")).toContainText("$1,000.00");
  await page.reload();
  await page.getByRole("button", { name: "More", exact: true }).click();
  await page.getByRole("button", { name: "Progress", exact: true }).filter({ visible: true }).click();
  await expect(page.locator(".actual-progress-summary")).toContainText("$1,000.00");
  await page.getByText("Account details & activity", {exact:true}).click();
  await expect(page.getByText("Removed from Debts · last balance retained", { exact: true })).toBeVisible();
});
