import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFileSync,mkdirSync} from 'node:fs';

test('everyday workflows keep independent targets, linked balances, Undo, and temporary scenarios',async({page},info)=>{
 const fixture=JSON.parse(readFileSync('tests/fixtures/legacy-v0.json','utf8'));
 fixture.transactions=[];fixture.balanceAdjustments=[];
 fixture.accounts=[{...fixture.accounts[0],id:'everyday',name:'Everyday Card',balance:5000,baselineBalance:6250,minimum:150,minimumMode:'manual',apr:22,interestFee:0,dueDate:'2026-08-17',promoEndDate:'',postPromoApr:0},{...fixture.accounts[0],id:'second',name:'Second Card',balance:3000,baselineBalance:3750,minimum:100,minimumMode:'manual',apr:18,interestFee:0,promoEndDate:'',postPromoApr:0}];
 fixture.monthlyPlan={detailedSpendingTracking:false,months:{},payoffPlanAmount:600,payoffPlanStrategy:'avalanche',progressStartingBalance:10000};
 fixture.snapshots=[{...fixture.snapshots[0],totalBalance:10000,month:'2026-07',accounts:fixture.accounts.map((a:{id:string;name:string;type:string;baselineBalance:number;apr:number})=>({accountId:a.id,name:a.name,type:a.type,balance:a.baselineBalance,apr:a.apr}))}];
 await page.goto('/');await page.locator('input[type=file]').setInputFiles({name:'disposable-usability.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});
 const card=page.locator('.compact-debt-card').filter({hasText:'Everyday Card'});
 await expect(card.locator('.simple-balance')).toHaveText('$5,000.00');
 const screenshot=async(name:string)=>{mkdirSync('../implemented-screens',{recursive:true});await page.screenshot({path:`../implemented-screens/${info.project.name}-${name}.png`,fullPage:false});};
 await screenshot('debts');
 await card.getByRole('button',{name:'Edit debt details for Everyday Card'}).press('Enter');
 await expect(page.getByRole('dialog').getByRole('heading')).toHaveText('Everyday Card');
 await page.getByRole('button',{name:'Close account form'}).click();
 await card.getByRole('button',{name:'Activity for Everyday Card'}).press('Enter');
 await expect(page.getByRole('dialog')).toContainText('No activity yet.');await page.getByRole('button',{name:'Close activity'}).click();
 await page.getByRole('button',{name:'Debt +',exact:true}).click();
 await expect(page.getByRole('dialog').getByLabel('Current balance')).toBeVisible();
 await expect(page.getByRole('dialog').getByLabel('Due date')).not.toBeVisible();
 await screenshot('add-debt');await page.getByRole('button',{name:'Close account form'}).click();
 await card.getByRole('button',{name:'Update balance for Everyday Card'}).click();
 await page.getByLabel('New current balance').fill('4500');await page.getByRole('button',{name:'Confirm balance update'}).click();
 await card.getByRole('button',{name:'Record payment for Everyday Card'}).click();
 await expect(page.getByLabel('Payment debt')).toHaveValue('everyday');
 await page.getByLabel('Payment amount').fill('150');await page.getByRole('button',{name:'Confirm payment'}).click();
 await expect(page.getByRole('dialog')).toContainText('This payment may already be included');await screenshot('overlap');
 await page.getByRole('button',{name:'Already included in that update'}).click();await page.getByRole('button',{name:'Confirm payment'}).click();
 await expect(card.locator('.simple-balance')).toHaveText('$4,500.00');
 await page.locator('.entry-undo').getByRole('button',{name:'Undo'}).click();await expect(card.locator('.simple-balance')).toHaveText('$4,500.00');
 await card.getByRole('button',{name:'Record payment for Everyday Card'}).click();await page.getByLabel('Payment amount').fill('150');await page.getByRole('button',{name:'Confirm payment'}).click();await page.getByRole('button',{name:'This is another payment'}).click();await page.getByRole('button',{name:'Confirm payment'}).click();await expect(card.locator('.simple-balance')).toHaveText('$4,350.00');
 await page.locator('.entry-undo').getByRole('button',{name:'Undo'}).click();await expect(card.locator('.simple-balance')).toHaveText('$4,500.00');
 await page.getByRole('button',{name:'Transactions',exact:true}).click();await page.getByRole('button',{name:'Add record',exact:true}).click();
 await page.getByLabel('What’s it for?',{exact:true}).fill('Grocery run');await page.getByLabel('Transaction amount').fill('+66.96');
 await expect(page.getByRole('dialog')).toContainText('Debt increases by $66.96');await expect(page.getByRole('dialog')).toContainText('$4,566.96');
 await screenshot('transaction');await page.getByRole('button',{name:'Use negative amount'}).click();
 await expect(page.getByRole('dialog')).toContainText('Debt decreases by $66.96');await page.getByRole('button',{name:'Use positive amount'}).click();await page.getByRole('button',{name:'Save transaction',exact:true}).click();
 await page.locator('.entry-undo').getByRole('button',{name:'Undo'}).click();
 await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('button',{name:'Payoff Calculator',exact:true}).click();
 await page.getByLabel('Total monthly debt payment',{exact:true}).fill('700');await screenshot('calculator');
 await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('button',{name:'Payoff Plan',exact:true}).click();
 await expect(page.getByLabel('Total monthly debt payment',{exact:true})).toHaveValue('600');await expect(page.locator('.allocation-recorded').first()).toContainText('$0.00');
 await screenshot('plan');
 await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('button',{name:'Payoff Calculator',exact:true}).click();await page.getByRole('button',{name:'Use this in my plan'}).click();await expect(page.getByLabel('Total monthly debt payment',{exact:true})).toHaveValue('700');
 await page.getByRole('button',{name:'More',exact:true}).click();await page.getByRole('button',{name:'Progress',exact:true}).filter({visible:true}).click();
 await expect(page.locator('.actual-progress-summary')).toContainText('$10,000.00');await expect(page.locator('.actual-progress-summary')).toContainText('$7,500.00');await expect(page.locator('.actual-progress-summary')).toContainText('$2,500.00');
 await expect(page.locator('.progress-snapshot-chart circle')).toHaveCount(1);await expect(page.getByRole('button',{name:'Save snapshot',exact:true})).toBeVisible();await screenshot('progress');
 const axe=await new AxeBuilder({page}).include('.actual-progress-screen').withRules(['color-contrast']).analyze();expect(axe.violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
