"use client";
import { useState } from "react";
import type { BalanceAdjustment, DebtAccount, LedgerTransaction, PayoffSnapshot, RemovedProgressAccount } from "./dashboard-data";
import type { LoanTracker } from "./loan-progress";
import LoanActivityPanel from "./loan-activity-panel";
import { loanProgress } from "./loan-progress";
import { buildActualProgress, recentDebtMonths } from "./debt-activity";
import DebtActivityPanel, { activityMonthLabel } from "./debt-activity-panel";
const money = new Intl.NumberFormat("en-US", {style:"currency",currency:"USD"});
const change = (amount: number) => `${money.format(Math.abs(amount))} ${amount >= 0 ? "lower" : "higher"}`;
function ProgressBar({name, starting, current}: {name:string;starting:number;current:number}) {
 const percent=starting>0?Math.max(0,Math.min(100,(starting-current)/starting*100)):0;
 return <div className="actual-progress-bar" role="progressbar" aria-label={`${name} balance reduction`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Number(percent.toFixed(1))}><i style={{width:`${percent}%`}}/></div>;
}
export default function ActualProgressPage({accounts,transactions,adjustments,snapshots,loans,startingBalance,removedAccounts=[],readOnly=false,onLoanSnapshot,onCapture,onDelete,onUpdateNote,onAccounts}: {accounts:DebtAccount[];transactions:LedgerTransaction[];adjustments:BalanceAdjustment[];snapshots:PayoffSnapshot[];loans:LoanTracker[];startingBalance?:number;removedAccounts?:RemovedProgressAccount[];readOnly?:boolean;onLoanSnapshot?:()=>void;onCapture:(note:string)=>void;onDelete:(id:string)=>void;onUpdateNote:(id:string,note:string)=>void;onAccounts:()=>void}) {
 const report=buildActualProgress(accounts,transactions,adjustments,snapshots,new Date(),startingBalance,removedAccounts);
 const [note,setNote]=useState(() => snapshots.find(snapshot => snapshot.month === recentDebtMonths()[0])?.note ?? "");
 const months=recentDebtMonths();
 const [scope,setScope]=useState<"cards"|"loans">("cards");
 const comparisonIds = (report.baseline?.accounts.map(a=>a.accountId) ?? report.groups.flatMap(group=>group.accounts.map(a=>a.id))).sort().join("|");
 const history=report.snapshots.filter(s=>s.accounts.map(a=>a.accountId).sort().join("|")===comparisonIds).map(s=>({month:s.month,balance:s.totalBalance}));
 const max=Math.max(1,...history.map(p=>p.balance));
 const x=(i:number)=>history.length<2?300:40+i/(history.length-1)*520;
 const y=(balance:number)=>160-balance/max*130;
 return <div className="screen snapshots-screen actual-progress-screen"><div className="screen-title"><div><span className="eyebrow">Actual balances</span><h1>Progress</h1></div></div>
 {!accounts.length&&!removedAccounts.length&&!loans.length?<section className="large-empty"><h2>Add a debt to start tracking progress</h2><button className="primary" onClick={onAccounts}>Add debt</button></section>:<>
 <div className="debt-tabs" role="group" aria-label="Progress scope"><button type="button" aria-pressed={scope==="cards"} onClick={()=>setScope("cards")}>Cards &amp; other</button><button type="button" aria-pressed={scope==="loans"} onClick={()=>setScope("loans")}>House &amp; car</button></div>
 {scope==="cards"&&(accounts.length>0 || removedAccounts.length>0)&&<>

<section className="actual-progress-summary progress-story" aria-label="Actual debt progress"><span>Debt reduced · Cards &amp; other</span><strong>{report.comparisonAvailable?money.format(report.reduction):"Comparison unavailable"}</strong><p>{(report.starting>0?report.reduction/report.starting*100:0).toFixed(1)}% reduced</p><ProgressBar name="Total tracked debt" starting={report.starting} current={report.current}/><dl><div><dt>Starting balance</dt><dd>{report.starting>0?money.format(report.starting):"Unavailable"}</dd></div><div><dt>Current balance</dt><dd>{money.format(report.current)}</dd></div></dl>{report.retainedCount>0&&<small>Includes last balances of {report.retainedCount} removed accounts.</small>}</section>
 <section className="actual-month-card progress-month-story"><h2>Recent changes · {activityMonthLabel(months[0])}</h2><strong>{report.monthEntries.length?`${money.format(Math.abs(report.monthlyChange))} ${report.monthlyChange<=0?"net decrease":"net increase"}`:"No activity recorded"}</strong><p>{report.reductionCount} debt reduction{report.reductionCount===1?"":"s"} recorded this month.</p><details><summary>Activity breakdown</summary><dl><div><dt>Recorded payments</dt><dd>{money.format(report.monthEntries.filter(r=>r.kind==="payment").reduce((sum,r)=>sum+r.amount,0))}</dd></div><div><dt>Purchases</dt><dd>{money.format(report.monthEntries.filter(r=>r.kind==="purchase").reduce((sum,r)=>sum+r.amount,0))}</dd></div><div><dt>Interest &amp; fees</dt><dd>{money.format(report.monthEntries.filter(r=>r.kind==="interest"||r.kind==="fee").reduce((sum,r)=>sum+r.amount,0))}</dd></div><div><dt>Adjustments</dt><dd>{money.format(report.monthEntries.filter(r=>r.kind==="adjustment").reduce((sum,r)=>sum+r.difference,0))}</dd></div><div><dt>Debt reductions</dt><dd className="balance-down">−{money.format(report.monthlyReductions)}</dd></div><div><dt>Debt increases</dt><dd className="balance-up">+{money.format(report.monthlyIncreases)}</dd></div></dl></details></section>
 <section className="actual-history-card snapshot-controls" aria-label="Snapshots"><h2>Historical snapshots ({snapshots.length})</h2><details className="snapshot-note"><summary>Add a note — optional</summary><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={240}/></label></details><button className="secondary" disabled={readOnly} onClick={()=>onCapture(note)}>{snapshots.some(s=>s.month===months[0])?"Update this month's snapshot":"Save snapshot"}</button>{[...report.snapshots].reverse().map(snapshot=><SavedCheck key={snapshot.id} snapshot={snapshot} onDelete={onDelete} readOnly={readOnly} onUpdateNote={onUpdateNote}/>)}</section>
 <section className="actual-history-card progress-snapshot-chart"><h2>Historical snapshots · Cards &amp; other</h2>{history.length>=1?<><svg viewBox="0 0 600 200" role="img" aria-label="Actual tracked debt at saved balance checks"><polyline points={history.map((p,i)=>`${x(i)},${y(p.balance)}`).join(" ")} fill="none" stroke="#166534" strokeWidth="3"/>{history.map((p,i)=><g key={p.month}><circle cx={x(i)} cy={y(p.balance)} r="4" fill="#166534"><title>{activityMonthLabel(p.month)}: {money.format(p.balance)}</title></circle>{(i===0||i===history.length-1)&&<text x={x(i)} y="190" textAnchor={i===0?"start":"end"}>{activityMonthLabel(p.month)}</text>}</g>)}</svg><p>Saved balances for the same account set.</p></>:<p>Save a snapshot to build history.</p>}
</section>


 <details className="progress-account-details"><summary>Account details &amp; activity</summary><h2 className="progress-section-heading">Which accounts changed?</h2>

 {report.groups.filter(g=>g.accounts.length).map(group=><section className="actual-progress-group" key={group.group}><header><h2>{group.group}</h2><div><strong>{money.format(group.current)}</strong><small>{group.accounts.every(a => a.baselineBalance !== undefined) ? change(group.reduction) + " from saved starting balances" : "Starting comparison unavailable"}</small></div></header><div className="actual-account-grid progress-account-list">{group.accounts.map(account=><article key={account.id}><h3>{account.name}</h3>{account.removedFromDebts === true && <small>Removed from Debts · last balance retained</small>}<strong className="progress-account-change">{account.baselineBalance === undefined ? "Starting balance unavailable" : change(account.baselineBalance-account.balance)}</strong><details className="progress-account-numbers"><summary>Balance details ›</summary><dl><div><dt>Started at</dt><dd>{account.baselineBalance === undefined ? "Unavailable" : money.format(account.baselineBalance)}</dd></div><div><dt>Now</dt><dd>{money.format(account.balance)}</dd></div><div><dt>Balance change</dt><dd>{account.baselineBalance === undefined ? "Unavailable" : change(account.baselineBalance-account.balance)}</dd></div></dl></details><ProgressBar name={account.name} starting={account.baselineBalance??account.balance} current={account.balance}/><DebtActivityPanel accountId={account.id} name={account.name} transactions={transactions} adjustments={adjustments}/></article>)}</div></section>)}
 </details></>}
 {scope==="loans"&&loans.length>0&&<><section className="actual-progress-summary progress-story" aria-label="House and car progress"><span>Debt reduced · House &amp; car</span><strong>{money.format(loans.reduce((sum,l)=>sum+l.originalAmount-l.remainingAmount,0))}</strong><p>{(loans.reduce((sum,l)=>sum+l.originalAmount,0)>0?(1-loans.reduce((sum,l)=>sum+l.remainingAmount,0)/loans.reduce((sum,l)=>sum+l.originalAmount,0))*100:0).toFixed(1)}% reduced</p><dl><div><dt>Starting balance</dt><dd>{money.format(loans.reduce((sum,l)=>sum+l.originalAmount,0))}</dd></div><div><dt>Current balance</dt><dd>{money.format(loans.reduce((sum,l)=>sum+l.remainingAmount,0))}</dd></div></dl></section><section className="snapshot-controls actual-history-card"><h2>Historical snapshots · House &amp; car</h2><button type="button" className="secondary" disabled={readOnly} onClick={onLoanSnapshot}>Save snapshot</button>{loans.map(loan=><details key={loan.id}><summary>{loan.name} · {loan.history.length} saved records</summary>{loan.history.map((entry,i)=><p key={i}>Balance date {entry.date} · {money.format(entry.amount)}<br/>Saved {entry.recordedAt&&!Number.isNaN(Date.parse(entry.recordedAt))?new Date(entry.recordedAt).toLocaleString():"date unavailable"}</p>)}</details>)}</section><section className="actual-progress-group"><h2>House & car</h2><div className="actual-account-grid">{loans.map(loan=>{const progress=loanProgress(loan);return <article key={loan.id}><h3>{loan.name}</h3><dl><div><dt>Original loan</dt><dd>{money.format(loan.originalAmount)}</dd></div><div><dt>Remaining {loan.balanceKind==='payoff'?'payoff quote':'principal'}</dt><dd>{money.format(loan.remainingAmount)}</dd></div><div><dt>Reduced</dt><dd>{money.format(progress.reduction)} · {progress.percent.toFixed(1)}%</dd></div></dl><ProgressBar name={loan.name} starting={loan.originalAmount} current={loan.remainingAmount}/><small>As of {loan.asOf}{loan.balanceKind==='payoff'?' · Payoff quotes can include accrued interest or fees.':''}</small><LoanActivityPanel loan={loan}/></article>})}</div></section></>}
 </>}
 </div>;
}
function SavedCheck({snapshot,onDelete,onUpdateNote,readOnly}:{snapshot:PayoffSnapshot;readOnly:boolean;onDelete:(id:string)=>void;onUpdateNote:(id:string,note:string)=>void}) {
 const [note,setNote]=useState(snapshot.note);
 return <details className="saved-check"><summary><span>{activityMonthLabel(snapshot.month)} · {money.format(snapshot.totalBalance)}</span><small>Saved {snapshot.capturedAt && !Number.isNaN(Date.parse(snapshot.capturedAt)) ? new Date(snapshot.capturedAt).toLocaleString("en-US", {dateStyle:"medium",timeStyle:"short"}) : "date unavailable"}</small></summary><p>Balance period: {activityMonthLabel(snapshot.month)}</p>{Array.isArray(snapshot.revisions) && snapshot.revisions.length > 0 && <details><summary>Prior saved checks ({snapshot.revisions.length})</summary>{snapshot.revisions.map((version,i)=><p key={i}>{String(version.capturedAt)} · {money.format(Number(version.totalBalance))} · {version.accounts.map((a: {name:string;balance:number})=>`${a.name}: ${money.format(a.balance)}`).join("; ")}</p>)}</details>}<ul>{snapshot.accounts.map(a=><li key={a.accountId}>{a.name}: {money.format(a.balance)}</li>)}</ul><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={240}/></label><button className="secondary" disabled={readOnly||note===snapshot.note} onClick={()=>onUpdateNote(snapshot.id,note)}>Save note</button><button className="secondary" disabled={readOnly} onClick={()=>onDelete(snapshot.id)}>Delete balance check</button></details>;
}
