"use client";
import { useState } from "react";
import type { BalanceAdjustment, DebtAccount, LedgerTransaction, PayoffSnapshot } from "./dashboard-data";
import type { LoanTracker } from "./loan-progress";
import LoanActivityPanel from "./loan-activity-panel";
import { loanProgress } from "./loan-progress";
import { buildActualProgress, recentDebtMonths } from "./debt-activity";
import DebtActivityPanel, { activityMonthLabel } from "./debt-activity-panel";
const money = new Intl.NumberFormat("en-US", {style:"currency",currency:"USD"});
const change = (amount: number) => `${money.format(Math.abs(amount))} ${amount >= 0 ? "lower" : "higher"}`;
function ProgressBar({name, starting, current}: {name:string;starting:number;current:number}) {
 const percent=starting>0?Math.max(0,Math.min(100,(starting-current)/starting*100)):0;
 return <div className="actual-progress-bar" role="progressbar" aria-label={`${name} balance reduction`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Number(percent.toFixed(1))}><i style={{width:`${percent}%`}}/></div>;
}
export default function ActualProgressPage({accounts,transactions,adjustments,snapshots,loans,onCapture,onDelete,onUpdateNote,onAccounts}: {accounts:DebtAccount[];transactions:LedgerTransaction[];adjustments:BalanceAdjustment[];snapshots:PayoffSnapshot[];loans:LoanTracker[];onCapture:(note:string)=>void;onDelete:(id:string)=>void;onUpdateNote:(id:string,note:string)=>void;onAccounts:()=>void}) {
 const report=buildActualProgress(accounts,transactions,adjustments,snapshots);
 const [note,setNote]=useState("");
 const months=recentDebtMonths();
 const history=report.snapshots.map(s=>({month:s.month,balance:s.totalBalance}));
 if(history.at(-1)?.month===months[0]) history.pop();
 history.push({month:months[0],balance:report.current});
 const max=Math.max(1,...history.map(p=>p.balance));
 const x=(i:number)=>history.length<2?300:40+i/(history.length-1)*520;
 const y=(balance:number)=>160-balance/max*130;
 return <div className="screen snapshots-screen actual-progress-screen"><div className="screen-title"><div><span className="eyebrow">Actual balances</span><h1>Progress</h1><p>How much your tracked debt has changed. Calculator forecasts are on Payoff Plan.</p></div></div>
 {!accounts.length&&!loans.length?<section className="large-empty"><h2>Add a debt to start tracking progress</h2><button className="primary" onClick={onAccounts}>Add debt</button></section>:<>
 {accounts.length>0&&<><section className="actual-progress-summary" aria-label="Actual debt progress"><article><span>Starting tracked debt</span><strong>{money.format(report.starting)}</strong><small>Original tracking balances · {report.baselineDate ?? "Start date unavailable"}</small></article><article><span>Current tracked debt</span><strong>{money.format(report.current)}</strong><small>Current card and account balances · loans shown separately</small></article><article><span>{report.reduction>=0?"Debt reduced":"Debt increased"}</span><strong>{money.format(Math.abs(report.reduction))}</strong><small>{report.percent.toFixed(1)}% reduced since tracking began</small></article></section><ProgressBar name="Total tracked debt" starting={report.starting} current={report.current}/><p className="activity-explanation">Starting amounts stay fixed when monthly balance checks are saved. Adding or removing a debt changes the set of accounts being tracked. Balance reduction is net of payments, purchases, interest, and corrections.</p>
 <section className="actual-month-card"><h2>{activityMonthLabel(months[0])}</h2><strong>{report.monthEntries.length?`${money.format(Math.abs(report.monthlyChange))} ${report.monthlyChange<=0?"net decrease":"net increase"}`:"No activity recorded"}</strong><p>{report.paymentCount} payment{report.paymentCount===1?"":"s"} recorded this month. Includes saved balance updates without deducting them twice.</p><small>Recorded activity only. Missing payments or interest cannot be inferred from an unconfirmed balance update.</small></section>
 {report.groups.filter(g=>g.accounts.length).map(group=><section className="actual-progress-group" key={group.group}><header><h2>{group.group}</h2><div><strong>{money.format(group.current)}</strong><small>{change(group.reduction)} since tracking began</small></div></header><div className="actual-account-grid">{group.accounts.map(account=><article key={account.id}><h3>{account.name}</h3><dl><div><dt>Started at</dt><dd>{money.format(account.baselineBalance??account.balance)}</dd></div><div><dt>Now</dt><dd>{money.format(account.balance)}</dd></div><div><dt>Balance change</dt><dd>{change((account.baselineBalance??account.balance)-account.balance)}</dd></div></dl><ProgressBar name={account.name} starting={account.baselineBalance??account.balance} current={account.balance}/><DebtActivityPanel accountId={account.id} name={account.name} transactions={transactions} adjustments={adjustments}/></article>)}</div></section>)}
 <section className="actual-history-card"><h2>Saved balance history</h2>{history.length>=2?<><svg viewBox="0 0 600 200" role="img" aria-label="Actual tracked debt at saved balance checks"><polyline points={history.map((p,i)=>`${x(i)},${y(p.balance)}`).join(" ")} fill="none" stroke="#166534" strokeWidth="3"/>{history.map((p,i)=><g key={p.month}><circle cx={x(i)} cy={y(p.balance)} r="4" fill="#166534"><title>{activityMonthLabel(p.month)}: {money.format(p.balance)}</title></circle>{(i===0||i===history.length-1)&&<text x={x(i)} y="190" textAnchor={i===0?"start":"end"}>{activityMonthLabel(p.month)}</text>}</g>)}</svg><p>Actual saved checks and today’s balance. No projected payoff line.</p></>:<p>Save a monthly balance check to build history. Your progress totals already update when you record activity or change balances.</p>}
 <details><summary>Monthly balance checks ({snapshots.length})</summary><label>Optional note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={240}/></label><button className="secondary" onClick={()=>onCapture(note)}>{snapshots.some(s=>s.month===months[0])?"Update this month's balance check":"Save this month's balance check"}</button>{[...report.snapshots].reverse().map(snapshot=><SavedCheck key={snapshot.id} snapshot={snapshot} onDelete={onDelete} onUpdateNote={onUpdateNote}/>)}</details></section></>}
 {loans.length>0&&<section className="actual-progress-group"><h2>House & car</h2><p>Lifetime reduction from each loan’s original amount, shown separately from card progress.</p><div className="actual-account-grid">{loans.map(loan=>{const progress=loanProgress(loan);return <article key={loan.id}><h3>{loan.name}</h3><dl><div><dt>Original loan</dt><dd>{money.format(loan.originalAmount)}</dd></div><div><dt>Remaining {loan.balanceKind==='payoff'?'payoff quote':'principal'}</dt><dd>{money.format(loan.remainingAmount)}</dd></div><div><dt>Reduced</dt><dd>{money.format(progress.reduction)} · {progress.percent.toFixed(1)}%</dd></div></dl><ProgressBar name={loan.name} starting={loan.originalAmount} current={loan.remainingAmount}/><small>As of {loan.asOf}{loan.balanceKind==='payoff'?' · Payoff quotes can include accrued interest or fees.':''}</small><LoanActivityPanel loan={loan}/></article>})}</div></section>}
 </>}
 </div>;
}
function SavedCheck({snapshot,onDelete,onUpdateNote}:{snapshot:PayoffSnapshot;onDelete:(id:string)=>void;onUpdateNote:(id:string,note:string)=>void}) {
 const [note,setNote]=useState(snapshot.note);
 return <details className="saved-check"><summary>{activityMonthLabel(snapshot.month)} · {money.format(snapshot.totalBalance)}</summary><p>Saved {snapshot.capturedAt.slice(0,10)}</p><ul>{snapshot.accounts.map(a=><li key={a.accountId}>{a.name}: {money.format(a.balance)}</li>)}</ul><label>Note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={240}/></label><button className="secondary" disabled={note===snapshot.note} onClick={()=>onUpdateNote(snapshot.id,note)}>Save note</button><button className="secondary" onClick={()=>onDelete(snapshot.id)}>Delete balance check</button></details>;
}
