"use client";
import { useEffect, useState } from "react";
import type { PlanSettlement } from "./dashboard-data";
export type SettlementRequest = { targetId: string; name: string; kind: "spending" | "minimum"; amount: number; source: "debit" | "included" };
export default function PlanSettlementDialog({ request, month, onClose, onSave }: { request: SettlementRequest; month: string; onClose: () => void; onSave: (entry: PlanSettlement) => void }) {
 const [amount, setAmount] = useState(String(request.amount));
 const [source, setSource] = useState(request.source);
 const today = new Date();
 const localToday = today.getFullYear() + "-" + String(today.getMonth()+1).padStart(2,"0") + "-" + String(today.getDate()).padStart(2,"0");
 const [date,setDate] = useState(localToday.startsWith(month) ? localToday : month + "-01");
 useEffect(() => { const close = (e: KeyboardEvent) => { if(e.key === "Escape") onClose(); }; window.addEventListener("keydown",close); return () => window.removeEventListener("keydown",close); },[onClose]);
 return <div className="modal-backdrop"><section className="modal debt-action-modal" role="dialog" aria-modal="true" aria-labelledby="settlement-title"><header><div><h2 id="settlement-title">{request.kind === "minimum" ? "Minimum already paid" : "Record paid expense"}</h2><p>{request.name}</p></div><button onClick={onClose} aria-label="Close paid record">×</button></header><form onSubmit={e => { e.preventDefault(); if(!Number.isFinite(Number(amount)) || Number(amount)<=0 || !date.startsWith(month+"-")) return; onSave({...request,source,amount:Math.round(Number(amount)*100)/100,date,id:crypto.randomUUID(),createdAt:new Date().toISOString()}); }}><div className="debt-action-form"><p><strong>Current debt balances will stay unchanged.</strong> {request.kind === "minimum" ? "Use this only when the payment has already cleared and is included in your current balance. It counts toward this month's minimum and payment target." : "Use this for spending paid from checking, or a card charge already included in your current balance. Do not record the same expense again in Transactions."}</p><div className="form-grid"><label><span>Amount already paid</span><input autoFocus type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)}/></label><label><span>Date paid</span><input type="date" required min={month+"-01"} max={month+"-"+new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()} value={date} onChange={e=>setDate(e.target.value)}/></label>{request.kind === "spending" && <label className="wide"><span>Paid using</span><select value={source} onChange={e=>setSource(e.target.value as "debit" | "included")}><option value="debit">Debit / checking — no debt change</option><option value="included">Credit card — already included in current balance</option></select></label>}</div></div><footer><span>This records history only. No money is moved.</span><div><button type="button" className="secondary" onClick={onClose}>Cancel</button><button type="submit" className="primary">Save paid record</button></div></footer></form></section></div>;
}
